firstChest:
  Price: 100
  command: crate giveKey beta %player% 1
secondChest:
  Price: 250
  command: crate giveKey blocky %player% 1
thirdChest:
  Price: 500
  command:

paperCustomData: 1000
firstChestSlotMaterial: BARRIER # CAPS!
firstChestName: "§eVote Kiste"
secondChestSlotMaterial: ENDER_CHEST # CAPS!
secondChestName: "§eKiste 2"
thirdChestSlotMaterial: SHULKER_BOX
thirdChestName: "§eKiste 3"
gemsMaterial: EMERALD
gemsName: "Du hast: %bpeco_gems% Gems!"



