database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    database: admin
    username: admin
    password: 1234
VoteCrate:
  Price: 100
Beta Kiste:
  Price: 250
EventCase:
  Price: 500

paperCustomData: 1000
firstChestSlotMaterial: BARRIER # CAPS!
firstChestName: "§eVote Kiste"
secondChestSlotMaterial: ENDER_CHEST # CAPS!
secondChestName: "§eKiste 2"
thirdChestSlotMaterial: ""
thirdChestName: "§eKiste 3"
gemsMaterial: EMERALD
gemsName: "Du hast: %bpeco_gems%"



